name: ginac-lean-codegen

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  codegen:
    name: ginac-lean-codegen
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # , macos-latest] # , windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.11
      - name: package install
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt update
            sudo apt install -y curl wget git git-lfs clang lld libc++-dev
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "Running on macOS"
          else
            echo "Unsupported OS"
          fi
      - name: pip install
        run: |
          pip install -r codegen/requirements.txt -r codegen/requirements-dev.txt -r codegen/requirements-tests.txt
      - name: run pre-commit
        run: |
          pre-commit run --all-files
      - name: run codegen tests
        run: |
          pytest codegen/tests
